jwt:
    iss: mylog.com
    secret: JEIvLVxBLzx8PkxVJDBGRiFDMzBcL2FSTjNBRTwrM2U
    access_token_exp: 86400

allow:
    paths: >
        /docs/**,
        /swagger-ui/**,
        /api-docs/**,
        /favicon**,
        /robot**

    origins: >
        http://localhost:5173,
        http://local.admin.irum.pumda.co:9002,
        https://admin.irum.pumda.co
