springdoc:
    packages-to-scan: com.pllis.mylog  # Swagger 문서를 생성할 컨트롤러가 포함된 패키지를 지정
    paths-to-match: /**  # 문서화할 경로를 지정합니다. /**는 모든 경로를 의미

    swagger-ui:
        path: docs  # 생성된 API 문서의 경로를 지정
    api-docs:
        path: /docs/json  # 생성된 API 문서의 경로를 지정
        groups:
            enabled: true  # 그룹별로 API 문서를 생성할지 여부 (기본값: true)
    cache:
        disabled: true  # Swagger 문서의 캐싱을 사용하지 않도록 설정 (기본값: false)

    # 기본적으로 사용할 요청 및 응답의 미디어 타입을 설정
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
